from pathlib import Path

from fate_mcp.contracts import generate_contract_artifacts
from fate_mcp.examples import build_examples
from fate_mcp.runtime import FateRuntime
from fate_mcp.validation import validate_generated_artifacts


def test_contract_generation_and_validation() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    generate_contract_artifacts(repo_root)
    results = validate_generated_artifacts(repo_root)
    assert all(item["status"] == "ok" for item in results["schemas"])
    assert all(item["status"] == "ok" for item in results["examples"])
    assert (repo_root / "docs" / "contracts" / "schemas" / "adapterImportManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "adapterUnitConversionRule.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "erosionSedimentMethodProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "erosionSedimentMethodProfileManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "fateRegionProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "importExternalResultPayloadRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyApplicabilityProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificValidationClaim.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificValidationClaimManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReferenceCase.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReferenceCaseManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificValidationClaimCoverageRecord.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificValidationClaimCoverageManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificMethodsDossierClaimSummary.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildScientificMethodsDossierRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificMethodsDossier.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildScientificMethodsDossierBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificMethodsDossierBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonProfileManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionProfileManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeReviewProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeReviewProfileManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "calculationTrace.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReviewProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReviewProfileManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "fateParameterPolicy.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "fateParameterPolicyFamily.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "previewRegulatoryHandoffResolutionRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffConsumerAliasManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "summarizeRegulatoryHandoffPackageRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildRegulatoryHandoffReviewBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildRegulatoryHandoffReviewPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildRunParameterManifestRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "runParameterManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildRunUncertaintySummaryRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "runUncertaintySummary.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildRunScientificTrustBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "runScientificTrustBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyComparisonPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyComparisonBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "previewModelFamilyComparisonReviewRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonReviewPreview.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyComparisonReviewPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonReviewPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyComparisonReviewBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyComparisonReviewBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "recommendModelFamilySelectionRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionRecommendation.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "previewModelFamilySelectionReviewRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionReviewPreview.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilySelectionReviewPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionReviewPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilySelectionReviewBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilySelectionReviewBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "previewModelFamilyChallengeReviewRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeReviewPreview.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyChallengeReviewPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeReviewPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyChallengeReviewBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeReviewBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyChallengeScientificDossierRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeScientificDossier.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildModelFamilyChallengeScientificDossierBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "modelFamilyChallengeScientificDossierBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "previewScientificReviewOutcomeRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReviewOutcomePreview.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildScientificReviewPacketRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReviewPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "buildScientificReviewBriefRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "scientificReviewBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffProfile.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffReviewBrief.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffPackageSummary.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffReviewPacket.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffResolutionPreview.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffTargetMatrixManifest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "recommendRegulatoryHandoffProfileRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffProfileRecommendation.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "regulatoryHandoffPackage.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "screenErosionTransportRelevanceRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "erosionTransportRelevanceResult.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "estimateSoilLossRusleRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "soilLossRusleResult.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "estimateEventSedimentYieldMusleRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "eventSedimentYieldMusleResult.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "estimateSedimentAssociatedChemicalLoadRequest.v1.json").exists()
    assert (repo_root / "docs" / "contracts" / "schemas" / "sedimentAssociatedChemicalLoadResult.v1.json").exists()


def test_build_examples_is_deterministic() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    runtime = FateRuntime(repo_root)
    assert build_examples(runtime) == build_examples(runtime)
